import numpy as np
from matplotlib import pyplot as plt

'''
This script simply plots the synthetic spectra generated by Starburst99 as a ionizing source for the Cloudy models.
'''

# the spectrum file
#spec = '../../../Addons/cloudy/c13.03all/c13.03/data/cSFRg40_lZ_sUV.stb99'
spec = '../../../Addons/cloudy/c13.03all/c13.03/data/cSFRg00_hZ_sUV.stb99'

time, waves, logtotal, logstellar, logneb = np.loadtxt(spec, skiprows=6, unpack=True)

total = 10**logtotal
stellar = 10**logstellar
nebular = 10**logneb

tim5, wav5, tot5, ste5, neb5 = [], [], [], [], []
tim8, wav8, tot8, ste8, neb8 = [], [], [], [], []

for t, w, lt, ls, ln in zip(time, waves, logtotal, logstellar, logneb):
    if t >= 2.0e7 and t < 4.0e7:
        tim5.append(t)
        wav5.append(w)
        tot5.append(lt)
        ste5.append(ls)
        neb5.append(ln)
    if t >= 1.0e8:
        tim8.append(t)
        wav8.append(w)
        tot8.append(lt)
        ste8.append(ls)
        neb8.append(ln)
        
print 'len(tot5) = ', len(tot5)

# plot
plt.title('Starburst99 cSFRg40_lZ_sUV spectrum')
plt.xlabel('Wavelength  [$\AA$]')
plt.ylabel('Flux  [ergs/s/cm$^2$/$\AA$]')
plt.xlim(900.0, 10000.0)
plt.ylim(38.0, 40.5)
plt.plot(wav5, tot5, 'k')
plt.plot(wav5, ste5, 'b:')
plt.plot(wav5, neb5, 'r--')
plt.plot(wav8, tot8, 'c')
plt.plot(wav8, ste8, 'm:')
plt.plot(wav8, neb8, 'y--')
plt.show()



print 'Done!'